### PR TITLE
Refactor: Admin Dashboard (Stack)

### PR DESCRIPTION
**Pull request by kezzayuno**
# Description

Please include a summary of the changes and the related issue. List any dependencies that are required for this change. List user story associated with pull request.

Satisfies the ability to add, delete, and modify authors.

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by Tommy-Sand — COMMENTED** [review]
I don't think you should be able to delete yourself

**Comment by Tommy-Sand** [comment]
I think it's a good idea to change logins as well when changing username

**Comment by kezzayuno** [comment]
Need to do: When you change a username I don't believe it changes the username in the login of that user, this would be important if the user was currently logged in

**Comment by kezzayuno** [comment]
> I don't think you should be able to delete yourself

Will do later on when other branches are merged to main

**Comment by Tommy-Sand** [comment]
> I think it's a good idea to change logins as well when changing username

To add onto this, this should also apply to deleting users, i.e., we should delete the logins of the deleted user

**Comment by Tommy-Sand** [comment]
We shouldn't let admins modify usernames to be instances of already existing usernames.

**Review by alinnmartinez — APPROVED** [review]
Reviewed -- it was mostly additions to new files and I didn't find anything to be missing or broken

**Pull request merged**
