### PR TITLE
Refactor: Accessing YoshiConnect, Follow, Friend, Request, Inbox, Author, Posts (Mostly)

### PR DESCRIPTION
**Pull request by kezzayuno**
# Description

Please include a summary of the changes and the related issue. List any dependencies that are required for this change. List user story associated with pull request.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kezzayuno** [comment]
Login and Signup are refactored. 

Existing issues related to other API endpoints: 
- Getting the correct username for the right navbar 
- Fetching the public posts 

Update:
- Prepared for scrapping the Welcome screen, public feed does not check for expiry anymore

**Comment by kezzayuno** [comment]
Schemas have also been updated for Author

**Comment by kezzayuno** [comment]
Removed Friend scheme, instead, we will opt to get Friends via comparing our Following and Follower schemes

**Comment by kezzayuno** [comment]
Some new api routes will be replaced by inbox, I just have them temporarily for now for testing.

**Comment by kezzayuno** [comment]
**For @Tommy-Sand **:
- I would suggest restarting the database soon 
- Axios refactor will be done after backend refactor is finished
- Runs but haven't tried logging in regular (admin works) 

**Admin:**
- Needs to test modify author, add author, delete author (once authors actually show up) 
- Will not show any authors because I am called the ```/api/authors``` endpoint, which is not working now.
- Logging out and logging in as an admin works
- Rejects and does not cache non-admins (sends 403) 
- Status is added and implemented, but the frontend still needs to make the 500 Page (console.log as a placeholder) 

**Friend:**
- Temporarily no friends to show for posts since we need the paging and posts in general to be done 

**Feeds Overall**:
- Need testing and most things will probably not show up due to either paging or backend unable to get the data correctly from the database

Login and Signup frontend and backend done for the most part.

**Comment by kezzayuno** [comment]
**Admin Checks**: 
- Paging for Authors (Prev and Back); stops when there is no more to show; Prev disabled when no Prev
- Adding an Author 
- Deleting an Author
- Modifying an Author 
- Only lets admin=true Authors in (403 otherwise)

**Comment by kezzayuno** [comment]
**Signup and Login Completed**:
- Signup works
- Login works

**Comment by kezzayuno** [comment]
**Still needs to be checked**
- Profile 
- Public
- Settings
- APIDocs
- Following
- Friends
- Navs
- Notifications / Requests
- Posts (excluding likes and comments)

**Comment by kezzayuno** [comment]
**Working but not tested thoroughly**: 
- Requests (Shows requests in notifications)
- Add works
- Not sure if reject works 
- Following list shows 
- Username shows on right nav

**Still need to check if broken on frontend**
- Profile (getting owner posts to show; unfriend, unfollow, Sent -> Add) 
- Public (getting public posts to show) 
- Settings
- APIDocs
- Friends (Showing friends list on left nav, getting true friend only posts for FriendsFeed)
- Posts (excluding likes and comments; creating a post, deleting a post, modifying post) 

**Unfinished backend, cannot test**:
- Likes 
- Comments

**Comment by kezzayuno** [comment]
**Will need to redo documentation for openAPI / Swagger.io**
- /api-docs is accessible

**Comment by kezzayuno** [comment]
Working but not tested thoroughly:
- Signup retested and works 
- Deleted the database, starting clean
- Following list shows 
- Login works
- PublicPosts connected; create post works 
- Public posts show even when not following anyone (i.e., PublicPosts); no duplicates if they are following someone 

**Still need to check and test**:
Profile (getting owner posts to show; unfriend, unfollow, Sent -> Add)
Settings
Friends (Showing friends list on left nav, getting true friend only posts for FriendsFeed)
Posts (deleting a post, modifying post)

**Unfinished backend, cannot test:**
- Likes
- Comments

**Needed**:
- Paging needed for fetching public posts

**Comment by kezzayuno** [comment]
**Working but not tested thoroughly:**
- Deleting post works 

**Still need to check and test:**
Profile (getting owner posts to show; unfriend, unfollow, Sent -> Add)
Settings
Friends (Showing friends list on left nav, getting true friend only posts for FriendsFeed)

**Unfinished backend, cannot test:**
- Likes
- Comments

**Needed:**
- Paging needed for fetching public posts
- Editing posts still not working and very difficult to debug

**Comment by kezzayuno** [comment]
**Working but not tested thoroughly:**
- Editing posts works 

**Still need to check and test:**
- Profile (getting owner posts to show; unfriend, unfollow, Sent -> Add)
- Settings
- Friends (Showing friends list on left nav, getting true friend only posts for FriendsFeed)

**Unfinished backend, cannot test:**
- Likes
- Comments

**Needed:**
- Paging needed for fetching public posts

**Comment by Tommy-Sand** [comment]
There is a bug where editing a post when debugging works but not in normal use. I believe it is due to the refresh that occurs.

**Comment by kezzayuno** [comment]
Working but not tested thoroughly:
- Settings are done (can modify personal attributes of account, can log out; still in construction: GitHub, Change Password (OPTIONAL))

**Still need to check and test:**
- Profile (getting owner posts to show; unfriend, unfollow, Sent -> Add)
- Friends (Showing friends list on left nav, getting true friend only posts for FriendsFeed)

**Unfinished backend, cannot test:**
- Likes
- Comments

**Needed:**
- Paging needed for fetching public posts
- When paging the posts, send over the likes and use that to calculate the counts for likes on a post as well as comments (reduces amount of requests required)

**Comment by kezzayuno** [comment]
**Working but not tested thoroughly:**
- Shows friends list on FriendsFeed and true friends posts in FriendsFeed

**Still need to check and test:**
- Profile (getting owner posts to show; unfriend, unfollow, Sent -> Add)

**Unfinished backend, cannot test:**
- Likes
- Comments

**Needed:**
- Paging needed for fetching public posts
- When paging the posts, send over the likes and use that to calculate the counts for likes on a post as well as comments (reduces amount of requests required)

**Comment by kezzayuno** [comment]
**Working but not tested thoroughly:**
- Profile can: show posts either person or viewing someone else's profile, unfollow, unfriend, unsend requests, send requests

**Note:** When viewing you PERSONAL profile, you can see unlisted and listed posts, but when viewing someone else's profile, you cannot see their unlisted posts.

**Unfinished backend, cannot test:**
- Likes
- Comments

**Needed:**
- Paging needed for fetching public posts
- When paging the posts, send over the likes and use that to calculate the counts for likes on a post as well as comments (reduces amount of requests required)

**Pull request merged**
