### PR TITLE
Controlling visibility (Backend)

### PR DESCRIPTION
**Pull request by kezzayuno**
# Description

Please include a summary of the changes and the related issue. List any dependencies that are required for this change. List user story associated with pull request.

Providing backend for checks on if the current viewer can view the post. This means, if the user tries to access a certain post and they find that they are not in the visibility (i.e., not a friend or private receiver), then it will get 404 Status. 

I refactored the update_post to update the post given that when the user presses edit post, the cells in the edit post are filled with the old values. 

I refactored friends, followings, and followers to also save authorIds for the sender and receiver. 

What needs to be done: Connect to frontend

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kezzayuno** [comment]
- Check who can view the post (i.e., PSA, followers only, friends only, private message to a specific person or friend-group)
- Check if there is a specification in the post component that differentiates between a post that is only for a specific person (private) or group (friend or stranger) 
-  If not: 
   - If visibility is private: list the people can can view the post (add a private (gives a list)), followers, public (PSA), friends)

**Comment by kezzayuno** [comment]
- Check if the person trying to view a post is a friend, follower, or its public (anyone can view); else: send 404 response or maybe forbidden

**Comment by kezzayuno** [comment]
Issue: Need to do edit visibility

**Comment by kezzayuno** [comment]
Issue: Refactor Friends and Followings and Followers to include the authorId

**Review by Holy-Hero — APPROVED** [review]
LGTM

**Pull request merged**
