### PR TITLE
React+node

### PR DESCRIPTION
**Pull request by niazieo**
# Description

This branch contains the basic build for ReactJS website with NodeJS backend. Some changes were made from KC's branch but not too heavy of changes. Just some edits in files to use the proper index.html

Make sure you are in the yoshi-connect folder:
```
Ex:
D:\Coding\CMPUT 404\yoshi-connect\>
```
To run locally first run:
```
npm install
```
Then run:
```
npm start
```
to start the server.

Next open a new terminal and cd into the `yoshi-react` folder:
```
cd yoshi-react
D:\Coding\CMPUT 404\yoshi-connect\yoshi-react>
```
Then run
```
npm i react-scripts
npm start
```
to run the webpage. The webpage is running on `localhost:3000` and the server is running on `localhost:8080`

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
It has not been tested.
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by kezzayuno** [comment]
When I ```npm start```, I got this error in the localhost: 
```Error: No default engine was specified and no extension was provided.
    at new View (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/view.js:61:11)
    at Function.render (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/application.js:587:12)
    at ServerResponse.render (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/response.js:1039:7)
    at /Users/kezziahayuno/Documents/yoshiconnect/server.js:14:14
    at Layer.handle [as handle_request] (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:346:12)
   ```

**Comment by Tommy-Sand** [comment]
> 

I was able to get the server working by changing line 5 of server.js to this.
image

However I am still unable to run npm start in the yoshi-react directory.

**Review by Tommy-Sand — APPROVED** [review]
This looks fine to me now

**Comment by kezzayuno** [comment]
Found this issue: 
```
Proxy error: Could not proxy request /favicon.ico from localhost:3000 to http://localhost:8080.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```

**Comment by kezzayuno** [comment]
Okay, another note: 

To not get the proxy issue: 
1. ```npm run start``` for the server 
2. ```npm start``` for the react

**Review by kezzayuno — APPROVED** [review]
LGTM

**Pull request merged**
