### PR TITLE
Mongodb

### PR DESCRIPTION
**Pull request by Tommy-Sand**
# Description
Added mongoose in order to connect to MongoDB. After installing dependencies you can run the server which will connect you the MongoDB database.

Dependencies added
    Mongoose
    Dotenv

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Tested on my own machine by running an instance of the server

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by kezzayuno** [comment]
Experienced this error: 
```
(node:48470) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
/Users/kezziahayuno/Documents/yoshiconnect/node_modules/mongoose/lib/connection.js:695
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
          ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at Connection.openUri (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/mongoose/lib/connection.js:695:11)
    at /Users/kezziahayuno/Documents/yoshiconnect/node_modules/mongoose/lib/index.js:411:10
    at /Users/kezziahayuno/Documents/yoshiconnect/node_modules/mongoose/lib/helpers/promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/mongoose/lib/helpers/promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/mongoose/lib/index.js:1285:10)
    at Mongoose.connect (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/mongoose/lib/index.js:410:20)
    at Object.<anonymous> (/Users/kezziahayuno/Documents/yoshiconnect/server.js:32:10)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)

Node.js v18.12.1
```

I was in the root directory and I ran: ```npm run start```.

**Comment by kezzayuno** [comment]
@niazieo Maybe try to deploy this before approving.

**Comment by niazieo** [comment]
> 

This error happens when you havent connected with the db. I've changed the settings on Atlas to allow access from anywhere since previously, you had to whitelist your own ip in order to connect to the db.

**Review by niazieo — APPROVED** [review]
lgtm. This branch successfully deploys on heroku as well.

**Comment by kezzayuno** [comment]
Note to future users: ATLAS_URI=... in your .env file.

**Comment by kezzayuno** [comment]
```
(node:52121) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Small warning we could probably easily resolve.

**Comment by Tommy-Sand** [comment]
> Note to future users: ATLAS_URI=... in your .env file.

This has been updated in the readme.

**Pull request merged**
