### PR TITLE
Token Refactor

### PR DESCRIPTION
**Pull request by kezzayuno**
# Description

Please include a summary of the changes and the related issue. List any dependencies that are required for this change. List user story associated with pull request.

Fixes # (issue)

## Type of change

Refactoring token functionality. 

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please do the following tests: 
**Sign Up**
1. Create an account with an existing username (```kc``` exists). Should fail and should not be added to database (neither login or authors).
2. Create a new account successfully. Should be added to database (authors and login) and should be directed to ```/feed```.
3. Try to go to ```/users/kc```. Should be successful. Nothing should pop up when inspecting, no crashes. Should know if you're viewing your own account or someone else's (in this case, you're viewing someone else). Now, try to go to your profile.
4. Try to go to ```/users/fgsdg```. Should be 404 not found, no crashes inspect or on server side. No proxy errors. 
5. Try to go to ```/dsfsdfsd```. Should be 404 not found, no crashes inspect or on server side. No proxy errors. 
6. Try to go to ```/admin/dashboard```. Should not be authorized (forbidden). 
7. Try to access ```/friends```. Should be successful. 
8. Log out (go back to ```/feed```). Should delete token from the database (login), should be successful. 
9. Try to access ```/users/kc``` and ```/feed``` when logged out. Should fail but not crash. Should be not authorized.

**Login**
1. Login with an account that does not exist. Should fail. No crash though. Token should not be cached in the database.
2. Login successfully using your account. Token should be cached and you should see ```/feed```. 
4. Test steps 3-9 from **Sign up**. 

**Admin** 
1. Login with a non-admin account (like the one you created in **Sign up**). Should fail but not crash. Token should not be cached.
2. Try to access: ```/admin/dashboard```. Should fail but should not crash (should be forbidden). 
3. Login with ```kc``` and ```123```. Should be successful, token should be cached.
4. Log out. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kezzayuno** [comment]
```
/Users/kezziahayuno/Documents/yoshiconnect/routes/author.js:105
    console.log(req.cookies);
                    ^

TypeError: Cannot read properties of undefined (reading 'cookies')
    at get_profile (/Users/kezziahayuno/Documents/yoshiconnect/routes/author.js:105:21)
    at /Users/kezziahayuno/Documents/yoshiconnect/server.js:79:3
    at Layer.handle [as handle_request] (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:284:15
    at param (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:421:3)

Node.js v18.12.1
```

**How to reproduce error:** 
1. Go to ```/login```. Enter username and password (successful). 
2. Log out. 
3. Login with username and password (same) => crashes.

**Comment by kezzayuno** [comment]
```
Debug: Checking the Expiry Date of Token
/Users/kezziahayuno/Documents/yoshiconnect/routes/author.js:105
    console.log(req.cookies);
                    ^

TypeError: Cannot read properties of undefined (reading 'cookies')
    at get_profile (/Users/kezziahayuno/Documents/yoshiconnect/routes/author.js:105:21)
    at /Users/kezziahayuno/Documents/yoshiconnect/server.js:79:3
    at Layer.handle [as handle_request] (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:284:15
    at param (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:421:3)

Node.js v18.12.1
```

From ```get_profile()``` when going to a profile.

**Comment by Tommy-Sand** [comment]
> ```
> /Users/kezziahayuno/Documents/yoshiconnect/routes/author.js:105
>     console.log(req.cookies);
>                     ^
> 
> TypeError: Cannot read properties of undefined (reading 'cookies')
>     at get_profile (/Users/kezziahayuno/Documents/yoshiconnect/routes/author.js:105:21)
>     at /Users/kezziahayuno/Documents/yoshiconnect/server.js:79:3
>     at Layer.handle [as handle_request] (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/layer.js:95:5)
>     at next (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/route.js:144:13)
>     at Route.dispatch (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/route.js:114:3)
>     at Layer.handle [as handle_request] (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/layer.js:95:5)
>     at /Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:284:15
>     at param (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:365:14)
>     at param (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:376:14)
>     at Function.process_params (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/router/index.js:421:3)
> 
> Node.js v18.12.1
> ```
> 
> **How to reproduce error:**
> 
>     1. Go to `/login`. Enter username and password (successful).
> 
>     2. Log out.
> 
>     3. Login with username and password (same) => crashes.

This has been fixed

**Comment by kezzayuno** [comment]
Screenshot 2023-02-16 at 6 53 01 PM

This happens when I try to access a profile that does not exist. For example, ```/users/tom```.

**Comment by kezzayuno** [comment]
Screenshot 2023-02-16 at 6 55 46 PM

In ```author.js```, did you mean to send back something here? This is in ```get_profile()```.

**Comment by kezzayuno** [comment]
When going to a profile, does it know if it is your own profile versus someone else's?

**Comment by kezzayuno** [comment]
Screenshot 2023-02-16 at 6 59 44 PM

In ```/admin```, I successfully logged in as a non-admin, and also got this error.

**Comment by kezzayuno** [comment]
Screenshot 2023-02-16 at 7 02 12 PM

When I log in successfully as an admin (using an admin account), I got these back, but my token was cached into the database this time.

**Comment by kezzayuno** [comment]
Screenshot 2023-02-16 at 7 03 45 PM

Going into ```/admin/dashboard``` successfully without being logged in with these errors. 

Also, crashed server. 

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/response.js:278:15)
    at /Users/kezziahayuno/Documents/yoshiconnect/auth.js:78:28
    at /Users/kezziahayuno/Documents/yoshiconnect/node_modules/mongoose/lib/model.js:5267:18
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9)
Emitted 'error' event on Function instance at:
    at /Users/kezziahayuno/Documents/yoshiconnect/node_modules/mongoose/lib/model.js:5269:15
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

Node.js v18.12.1
```

**Comment by Tommy-Sand** [comment]
> 



> When going to a profile, does it know if it is your own profile versus someone else's?

It should, but it'll probably be in the response as opposed to displayed on the screen

**Comment by kezzayuno** [comment]
When I try to access ```/users/kc```, which exists, it does what it is told, but there is this error. 

Screenshot 2023-02-16 at 7 05 42 PM

```
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/Users/kezziahayuno/Documents/yoshiconnect/node_modules/express/lib/response.js:278:15)
    at /Users/kezziahayuno/Documents/yoshiconnect/auth.js:78:28
    at /Users/kezziahayuno/Documents/yoshiconnect/node_modules/mongoose/lib/model.js:5267:18
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9)
Emitted 'error' event on Function instance at:
    at /Users/kezziahayuno/Documents/yoshiconnect/node_modules/mongoose/lib/model.js:5269:15
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

Node.js v18.12.1
kezziahayuno@Kezziahs-MacBook-Air yoshiconnect % npm run start

> yoshiconnect@1.0.0 start
> node server.js

Server listening on port 8080
Debug: Checking expiry of token
Debug: Checking the Expiry Date of Token
Debug: Checking expiry of token
Debug: Checking the Expiry Date of Token
Debug: Logging out as Author
Debug: Getting the token in the login database.
Debug: Login token deleted
Debug: Logging out as Author
Debug: Getting the token in the login database.
Debug: Login token deleted
Debug: Checking the Expiry Date of Token
Debug: Checking the Expiry Date of Token
Debug: Getting the token in the login database.
/Users/kezziahayuno/Documents/yoshiconnect/routes/author.js:111
                req.send(404);
                    ^

TypeError: req.send is not a function
    at /Users/kezziahayuno/Documents/yoshiconnect/routes/author.js:111:21
    at /Users/kezziahayuno/Documents/yoshiconnect/node_modules/mongoose/lib/model.js:5267:18
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.12.1
```

**Comment by kezzayuno** [comment]
> > 
> 
> > When going to a profile, does it know if it is your own profile versus someone else's?
> 
> It should, but it'll probably be in the response as opposed to displayed on the screen

Could you confirm if this is happening?

**Comment by kezzayuno** [comment]
Issue: 

When I log in as a regular user and go to ```/admin/dashboard```, it lets me.

**Comment by kezzayuno** [comment]
Issue: 

When I log out then go to ```/feed```, it shows the feed plus that it isn't cached anymore. It should just show a 401.

**Comment by kezzayuno** [comment]
Screenshot 2023-02-16 at 11 07 25 PM

For some reason, when I log in as someone that doesn't exist, it says the token is received. Probably just a console.log issue. It might confuse us later, so we should fix this now so we can trust our feedback.

**Comment by Tommy-Sand** [comment]
The last 3 issues have been fixed

**Comment by kezzayuno** [comment]
LGTM

**Pull request merged**
