### PR TITLE
Admin Setup

### PR DESCRIPTION
**Pull request by kezzayuno**
# Description

I have created a basic authentication "idea". So, essentially the authentication and visibility is controlled by whether a user is an author and also if they are an admin. I think we should have one token that we can check for that admins share. That would make logging in very simple (not heavy setup); protect this token of course. We will have to merge the database from the mongodb PR; there will be conflicts, haha.

This PR also has some TODOs that I think @Tommy-Sand could probably look into since they are database focused. When this PR is made, the database is not connected right now. I have an assumption on how the database will store authors. 

```
authors: [
{ authorId: 1234, username: 'Mill', pronouns: null, about: 'somethingsomething', email: 'milly@gmail.com'}
]
```

I am NOT sure about the admin token idea. Maybe the user should type the token. I also don't know how to approach passwords right now. 

I also decided we can make our admin page WITHOUT AdminJS. It shouldn't be complicated.

**User Stories Related:**
- [x] Create server admin page
- [x] Create authors
- [x] Save them in database (Login / Sign Up)
- [x] 27 As a server admin, I don’t want to do heavy setup to get the posts of my author’s friends.
- [x] 28 As a server admin, I want a restful interface for most operations
- [x] US SA.01 As a server admin, I want to host multiple authors on my server

Fixes # (issue)

Look at the TODOs. @Tommy-Sand if you have any questions on how I set it up, let me know. We can get into a call and I can explain it. I tried to comment as much as I could. 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kezzayuno** [comment]
**Update:**

So, now what I have done is added a section for sign up and log in. There are additional TODOs such as adding these signups to the database, etc.

**Comment by kezzayuno** [comment]
Not doing the token method; I decided it might be easier to have a header ```admin``` that stores a boolean that we can check.

**Comment by Tommy-Sand** [comment]
Largely completed authAuthor function and register_author. Additionally we should restrict the client to https and not allow sending data over http.

**Comment by kezzayuno** [comment]
Currently the authentication only works on localhost 8080

**Comment by kezzayuno** [comment]
Working as intended on localhost 8080 but not on localhost 3000

**Comment by kezzayuno** [comment]
Thinking of routing for the public feed -> friends -> messages -> profile -> settings, etc...

**Comment by kezzayuno** [comment]
Making super basic "nav bar" after login / signup

**Comment by kezzayuno** [comment]
> Still need to delete the cached token from db when the user logs out

Finished.

**Comment by kezzayuno** [comment]
Need to check expiry date when user tries to access the website again

**Comment by kezzayuno** [comment]
> Need to check expiry date when user tries to access the website again

Done, default set to 24 hours for now.

**Comment by kezzayuno** [comment]
> Making super basic "nav bar" after login / signup

Added.

**Comment by kezzayuno** [comment]
We need to implement a persistent nav bar to access all the logged in areas => under ```/feeds``` + ```/settings```

**Comment by Tommy-Sand** [comment]
I am getting this error after signing up 
image

**Comment by kezzayuno** [comment]
> I am getting this error after signing up image

Fixed!

**Comment by kezzayuno** [comment]
Possible issues: 
- Making multiple caches of a token for one account; Solution: Check if there is a token already cached for the user in login and admin

**Comment by kezzayuno** [comment]
Issue: 
- not-admin tries to login as admin and still saves their token even when they don't log in

**Comment by kezzayuno** [comment]
Try to access when not logged in = crash

**Comment by kezzayuno** [comment]
For profile = need a function to check if viewing our own profile or friend's profile

**Comment by kezzayuno** [comment]
Verify if using valid email conventions? 
Password requirements to satisfy?

**Comment by Tommy-Sand** [comment]
> * dmin

This issue has been fixed by checking if the token exists and if it does it will replace it with a new one

**Comment by Tommy-Sand** [comment]
There is an issue with log out wherein a user who is logged in will log out however this request is never sent to the server and this error message is printed in the console 

`Object { message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", config: {…}, request: XMLHttpRequest, response: {…}, stack: "" }
public.jsx:40
    checkExpiry public.jsx:40
    (Async: promise callback)
    checkExpiry public.jsx:38
    PublicFeed public.jsx:45
    React 8
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    (Async: EventHandlerNonNull)
    js scheduler.development.js:571
    js scheduler.development.js:633
    factory react refresh:6
    Webpack 24
`

**Comment by kezzayuno** [comment]
> Issue:
> 
> * not-admin tries to login as admin and still saves their token even when they don't log in

Fixed!

**Comment by kezzayuno** [comment]
> Try to access when not logged in = crash

Fixed.

**Comment by kezzayuno** [comment]
> For profile = need a function to check if viewing our own profile or friend's profile

Fixed. HOWEVER, the ```personal``` attribute is not updated. Might need to get a fix on that later when working on the profile.

**Comment by kezzayuno** [comment]
Password requirements to satisfy?

**Comment by kezzayuno** [comment]
Making the user confirm their password (i.e., type their password till password requirements are satisfied then typing password again to confirm if they typed it correctly).

**Comment by kezzayuno** [comment]
Password Requirements

**Comment by kezzayuno** [comment]
Check if username is already in use when signing up

**Comment by niazieo** [comment]
Atlas URI may need to have the it's last parameter removed

**Comment by kezzayuno** [comment]
Signup requires expiry date in login

**Comment by kezzayuno** [comment]
> Signup requires expiry date in login

Fixed.

**Comment by kezzayuno** [comment]
> There is an issue with log out wherein a user who is logged in will log out however this request is never sent to the server and this error message is printed in the console
> 
> image

Still unsolved?

**Comment by Tommy-Sand** [comment]
> 

Has now been fixed

**Comment by kezzayuno** [comment]
For the log out issue, could you do the fix also for the admin-dashboard section?

**Comment by Tommy-Sand** [comment]
> For the log out issue, could you do the fix also for the admin-dashboard section?

Sure

**Comment by kezzayuno** [comment]
Heroku not deploying correctly; needs fix.

**Comment by kezzayuno** [comment]
Adding a visibility to the password (i.e., when I wanna see what I typed, I press that button, when I want it hidden, I press it again; default it is hidden)

**Comment by Tommy-Sand** [comment]
I've changed the log out functionality to remove items in local storage instead of setting them to "undefined"

**Comment by kezzayuno** [comment]
There are several pages that require to check if: 
- Author is logged in
- Whether their token is expired or not 

We need to reduce redundancy by having these checked on all pages that require it without copying and pasting the code.

**Comment by kezzayuno** [comment]
Move isPersonal to ```author.js``` (in ```routes```); there will need to be some refactoring there.

**Comment by kezzayuno** [comment]
When checking another person's profile ```/:username```, the user can input **any** name; even if the username or account DOES NOT exist. We need to somehow check for ```:username``` input to make sure that it exists before loading the page.

**Comment by kezzayuno** [comment]
Make basic ```.jsx``` files for: 
- 404 page UI triggered if the user inputs a URL that is not found
- 403 Forbidden page for unauthorized access attempts
- 401 code page when user tries to access login only pages

**Comment by kezzayuno** [comment]
> Make basic `.jsx` files for:
> 
> * 404 page UI triggered if the user inputs a URL that is not found
> * 403 Forbidden page for unauthorized access attempts
> * 401 code page when user tries to access login only pages

Done.

**Comment by kezzayuno** [comment]
Updated the user route to ```users/:username```

**Comment by kezzayuno** [comment]
> Adding a visibility to the password (i.e., when I wanna see what I typed, I press that button, when I want it hidden, I press it again; default it is hidden)

This is a frontend issue. I'll direct this issue to @niazieo and @alinnmartinez .

**Comment by kezzayuno** [comment]
> Check if username is already in use when signing up

Still need to get this done.

**Comment by kezzayuno** [comment]
> > For profile = need a function to check if viewing our own profile or friend's profile
> 
> Fixed. HOWEVER, the `personal` attribute is not updated. Might need to get a fix on that later when working on the profile.

Still need to explore this.

**Comment by kezzayuno** [comment]
> Heroku not deploying correctly; needs fix.

Will look into.

**Comment by kezzayuno** [comment]
> > Check if username is already in use when signing up
> 
> Still need to get this done.

Done

**Comment by kezzayuno** [comment]
> > > For profile = need a function to check if viewing our own profile or friend's profile
> > 
> > 
> > Fixed. HOWEVER, the `personal` attribute is not updated. Might need to get a fix on that later when working on the profile.
> 
> Still need to explore this.

Done.

**Comment by kezzayuno** [comment]
When inputting a random user that does not exist: ```/users/:username```, still shows page and not 404.

**Comment by kezzayuno** [comment]
> When inputting a random user that does not exist: `/users/:username`, still shows page and not 404.

Done.

**Comment by kezzayuno** [comment]
**Required Heroku Fixes:**
- Stop going to a user that does not exist (Login / Signup)
- Sending JSON instead of webpage (cannot log out) (Login / Signup) -> Check tomorrow in network tab
- Test: Try to access /users/kc and /feed when logged out. Should fail but not crash. Should be not authorized. (Once JSON fix is made) (Login / Signup)

**Required Local Fixes:**
- Change /api/:username => Retest Step 2 (Login / Sign up)
- update the other login only restricted pages using protectedroutes of some sort

**Comment by kezzayuno** [comment]
**Small Issue**
 Login caches multiple tokens for one author

**Comment by Holy-Hero** [comment]
### Testing
Only one bug found
- There is no pop-up when logging in with a non-admin on localhost while there is one for Heroku

**Review by Holy-Hero — APPROVED** [review]
Other than the alert() that KC said she'd remove it LGTM

**Comment by kezzayuno** [comment]
Please do the following tests: 
**Sign Up**
1. Create an account with an existing username (```kc``` exists). Should fail and should not be added to database (neither login or authors).
2. Create a new account successfully. Should be added to database (authors and login) and should be directed to ```/feed```.
3. Try to go to ```/users/kc```. Should be successful. Nothing should pop up when inspecting, no crashes. Should know if you're viewing your own account or someone else's (in this case, you're viewing someone else). Now, try to go to your profile.
4. Try to go to ```/users/fgsdg```. Should be 404 not found, no crashes inspect or on server side. No proxy errors. 
5. Try to go to ```/dsfsdfsd```. Should be 404 not found, no crashes inspect or on server side. No proxy errors. 
6. Try to go to ```/admin/dashboard```. Should not be authorized (forbidden). 
7. Try to access ```/friends```. Should be successful. 
8. Log out (go back to ```/feed```). Should delete token from the database (login), should be successful. 
9. Try to access ```/users/kc``` and ```/feed``` when logged out. Should fail but not crash. Should be not authorized.

**Login**
1. Login with an account that does not exist. Should fail. No crash though. Token should not be cached in the database.
2. Login successfully using your account. Token should be cached and you should see ```/feed```. 
4. Test steps 3-9 from **Sign up**. 

**Admin** 
1. Login with a non-admin account (like the one you created in **Sign up**). Should fail but not crash. Token should not be cached.
2. Try to access: ```/admin/dashboard```. Should fail but should not crash (should be forbidden). 
3. Login with ```kc``` and ```123```. Should be successful, token should be cached.
4. Log out.

**Comment by kezzayuno** [comment]
When checking for the user/sdhasd (not exist), it shows the profile briefly. We will fix this in new PR.

**Comment by kezzayuno** [comment]
I tested, and overall this was great. I think I will merge this PR now. Thanks for all the hard work everyone.

**Pull request merged**
